version: "3.8"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    ports:
        - "0.0.0.0:80:80"
    # Debug 
    # volumes:
    #   - ./static/:/usr/share/nginx/html/
